#!/usr/bin/env python
# 
# Jonathan Foote
# jmfoote@loyola.edu
#

import subprocess, re, sys, os, json, difflib

# see http://wiki.python.org/moin/PrintFails
import codecs, locale
sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout) 

def get_repo_path(path):
    if not os.path.isdir(path):
        path = os.path.dirname(path)
    return subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=path).strip()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.stderr.write("not enough args")
        sys.exit(-1)

    if len(sys.argv) > 2:
        cwd = sys.argv[2]
    else:
        cwd = "."

    shadow_repo_path = os.path.join(get_repo_path(cwd), ".shadow")
    if sys.argv[1] == "activate":
        if os.path.exists(shadow_repo_path):
            sys.stderr.write(".shadow already exists in %s" % shadow_repo_path) 
            sys.exit(-2)

        # make shadow repo
        subprocess.check_output(["git", "init", shadow_repo_path], cwd=cwd)

        # install git hooks
    elif sys.argv[1] == "deactivate":
        # remove git hooks
        # delete shadow repo
        subprocess.check_call(["rm", "-rf", shadow_repo_path], cwd=cwd)

        pass
    else:
        # run git command in mirror directory of shadow repo
        pass
