#!/usr/bin/env python

import sys, os, subprocess

shadow_git_repo_path = os.path.join(".shadow", ".git")
if not os.path.exists(shadow_git_repo_path):
    sys.stderr.write("git-shadow hook is installed, but shadow repository "
        " doesn't exist at '%s'. Try 'git shadow deactivate [repo]'." %\
        shadow_git_repo_path)
    sys.exit(-1)

# 1. rename shadow's git repository 
shadow_repo_storage_path = os.path.join(".shadow", "git")
shutil.move(shadow_git_repo_path, shadow_repo_storage_path)

# 2. git add shadow directory
subprocess.check_call(["git", "add", os.path.join(".shadow", "*")])
